project_core_add_message:
    pattern:  /message
    defaults: { _controller: ProjectBundleCoreBundle:Message:addMessage }
    requirements:
          _method: POST


project_core_get_message:
    pattern:  /message
    defaults: { _controller: ProjectBundleCoreBundle:Message:getMessage }

